lab/account/urls.py
from django.conf.urls import url, include
from .views import register, log_in, log_out

urlpatterns = [
    url(r'^register', register, name='register'),
    url(r'^login', log_in, name='login'),
    url(r'^logout', log_out, name='logout')
]

lab/lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='homepage'),
    url(r'^accounts/', include('account.urls', namespace='accounts')),
    url(r'^crm/', include('labcrm.urls', namespace='crm')),
    url(r'^webot/', include('webotconf.urls', namespace='webot')),
    url(r'^group/', include('group.urls', namespace='group')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/labcrm/urls.py
from django.conf.urls import url, include
from labcrm import views


ajax_urls = [
    url(r'^preview', views.ajax_conf_preview, name='preview'),
    # url(r'^modify', views.ajax_detail_modify, name='modify'),
    url(r'^add', views.ajax_conf_add, name='add'),
    url(r'^del', views.ajax_user_del, name='del'),
    url(r'^new', views.ajax_new_user, name='new')
]

modify_urls = [
    url(r'^schedule', views.modify_schedule, name='schedule')
]


urlpatterns = [
    url(r'^ajax/', include(ajax_urls, namespace='ajax')),
    url(r'^modify/', include(modify_urls, namespace='modify')),
    url(r'^users', views.user_list, name='list'),
    url(r'^userclass', views.user_class, name='userclass'),
    url(r'^detail/(?P<new_id>.*)$', views.user_detail, name='detail2'),
    url(r'^detail', views.user_detail, name='detail'),
    url(r'^papers', views.papers_create, name='papers'),
    url(r'^paper/(?P<data_key>\d*)$', views.paper_display, name='paper2'),
    url(r'^paper', views.paper_display, name='paper'),
    url(r'^conf', views.ques_conf, name='conf'),
    url(r'^fill/(?P<data_key>\d*)$', views.ques_fill, name='fill'),
    url(r'^fill', views.ques_fill, name='fill2'),
    url(r'^class', views.link_to_class, name='class'),
    url(r'^courses', views.learning_courses, name='courses'),
    url(r'^statistic', views.subject_statistic, name='statistic'),
    url(r'^schedule', views.schedule_statistic, name='schedule'),
]

lab/labcrm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms
from django.db.utils import IntegrityError
from django.db.models import Max
# from .admin import UsersResource
from collections import namedtuple
from PIL import Image
import base64
import json
import pymysql
import random
import datetime
# from mytool import log_this
from testools.declog import log_this, log_stack
# Create your views here.
from group.models import StudentGroup

picType = {
    'dialog': 'Dialog'
}
markPaper = {
    'tofill': 'TF',
    'default': 'DF'
}
# 课程状态，`期中项目` 与 `期末项目` 和数据库字段 school_chapter.title 对应
course_to_status = {
    '期中项目': (1, (True, False)),
    '期末项目': (2, (False, True)),
    '期末+期中': (3, (True, True)),
    '进行中': (0, (False, False)),
}
QuesTuple = namedtuple('QuesTuple', ['desc', 'aid', 'attr'])
QuesTuple2 = namedtuple('QuesTuple2', ['desc', 'aid', 'attr', 'value'])
crossin_db = ('47.93.61.70', 'markdev', 'mark2017', 'codeclass')


class ImgForm(forms.Form):
    pic = forms.ImageField()


def _save_uiq_uia(user, attr, answer):
    # 保存用户属性、值
    print('MODE: save')
    uiq, _ = UserInfoQ.objects.get_or_create(
        user=user, attr=attr
    )
    uia, is_new = UserInfoA.objects.get_or_create(
        user=user,
        question=uiq,
        is_del=False,
        defaults={'answer': answer}
    )
    print('uiq-uia-is_new_uia:\t', uiq, uia, is_new)
    if not is_new:
        uia.is_del = True
        uia.save()
        UserInfoA.objects.create(
            user=user,
            question=uiq,
            answer=answer
        )
    print('---------------')
    return uiq


@log_stack(2)
def get_class_id(nickname):
    """
    获取学习站用户ID
    """
    db = pymysql.connect(*crossin_db, charset="utf8")
    cur = db.cursor()
    cur.execute('''
        SELECT id FROM auth_user user
        WHERE user.username = '{username}'
    '''.format(username=nickname))
    cid = cur.fetchone()
    print('class_uid:\t', cid)
    if cid:
        cid = cid[0]
    else:
        cid = False
    return cid


@log_this
def _user_list_post(request):
    # username -> 本站用户名，    nickname -> 学习站用户名
    nickname = request.POST.get('nickname')
    wechat = request.POST.get('wechat')
    username = request.POST.get('username')
    is_update = request.POST.get('update')
    user, is_new = User.objects.get_or_create(username=username)
    print('nickname wechat username:\t', nickname, wechat, username)
    print('update is_new:\t', is_update, is_new)
    if is_update:
        if nickname:
            print('@添加用户名')
            cid = get_class_id(nickname)
            if cid:
                LabUser.objects.filter(user=user).update(nickname=nickname, class_id=cid)
            else:
                LabUser.objects.filter(user=user).update(nickname=nickname)
        elif wechat:
            print('@添加微信号')
            LabUser.objects.filter(user=user).update(wechat=wechat)
        lab_user = get_object_or_404(LabUser, user=user)
        # return render(request, 'labcrm/ajax/user_del.html', {
        #     'users': users
        # })
    elif is_new:
        print('@添加新用户')
        lab_user = LabUser.objects.create(
            user=user,
            wechat=wechat,
        )
        # return HttpResponse(render(request, 'labcrm/ajax/user_add.html', {
        #     'lab_user': users,
        # }))
    else:
        print('@昵称重复')
        return HttpResponse()
    return HttpResponse(render(request, 'labcrm/ajax/user_add.html', {
        'lab_user': lab_user,
    }))


@log_this
def _user_list_get(request):
    uid = request.GET.get('uid')
    print('uid:\t', uid)
    if uid:
        print('@用户数据修改')
        wechat = request.GET.get('wechat')
        username = request.GET.get('username')
        nickname = request.GET.get('nickname')
        ta = request.GET.get('ta')      # teaching assistant
        if wechat:
            print('wechat:\t', wechat)
            LabUser.objects.filter(id=uid).update(wechat=wechat)
        elif nickname:
            print('nickname:\t', nickname)
            cid = get_class_id(nickname)
            if cid:
                LabUser.objects.filter(id=uid).update(nickname=nickname, class_id=cid)
            else:
                LabUser.objects.filter(id=uid).update(nickname=nickname, class_id=None)
        elif ta:
            print('ta:\t', ta)
            LabUser.objects.filter(id=uid).update(ta=ta)
        else:
            print('username:\t', username)
            uuid = get_object_or_404(LabUser, id=uid).user.id
            try:
                User.objects.filter(id=uuid).update(username=username)
            except IntegrityError:
                return HttpResponse(1)
        return HttpResponse()
    elif request.GET.get('refresh'):
        print('@修改完毕，刷新列表')
        users = LabUser.objects.filter(is_del=False).order_by('-user__date_joined')
        return render(request, 'labcrm/ajax/user_del.html', {
            'users': users
        })
    elif request.GET.get('class') and request.GET.get('userid'):
        print('@修改学员类别')
        newclass = request.GET.get('class')
        user_id = request.GET.get('userid')
        try:
            print(user_id)
            print(newclass)
            LabUser.objects.filter(id=user_id).update(classification=newclass)
        except IntegrityError:
            return HttpResponse(1)
        return HttpResponse('.')
    print('@用户列表展示')
    users = LabUser.objects.filter(is_del=False).order_by('-user__date_joined')
    classification = LabUser.CLASS_CHOICES
    return render(request, 'labcrm/user_list.html', {
        'users': users,
        'classification': classification,
    })


@log_this
@login_required
def user_list(request):
    if request.method == 'POST':
        return _user_list_post(request)
    else:
        return _user_list_get(request)


@log_this
def _user_detail_get(request, lab_user):
    attrs = UserAttr.objects.all()
    attr_option = attrs.filter(is_option=True)
    dialogs = Dialog.objects.filter(user=lab_user).order_by('-log_time')
    pics = UserPic.objects.filter(user=lab_user, pic_type=picType['dialog'])
    user_answers = UserInfoA.objects.filter(user=lab_user, is_del=False)
    print('labUser:\t', lab_user)
    print('attrs:\t', attrs)
    print('attr_option:\t', attr_option)
    print('answers:\t', user_answers)
    print('dialogs-len:\t', len(dialogs))
    print('pics-len:\t', len(pics))
    if request.GET.get('ajax') is None:
        print('@用户信息展示')
        return render(request, 'labcrm/user_detail.html', {
            'labUser': lab_user,
            'attrs': attrs,
            'attr_option': attr_option,
            'answers': user_answers,
            'dialogs': dialogs,
            'pics': pics,
            'courses': LearningSchedule.COURSE_CHOICES,
            'schedules': LearningSchedule.SCHEDULE_CHOICES
        })
    else:
        print('@取消修改')
        return HttpResponse(render(request, 'labcrm/ajax_user_detail.html', {
            'labUser': lab_user,
            'attrs': attrs,
            'attr_option': attr_option,
            'answers': user_answers,
            'dialogs': dialogs,
            'pics': pics
        }))


@log_this
def _user_detail_post(request, lab_user):
    attrs = UserAttr.objects.all()
    attr_option = attrs.filter(is_option=True)
    dialog = request.POST.get('dialog')
    # pic_post = request.POST.get('pic')
    pic_name = request.POST.get('pic_name')
    questions = request.POST.getlist('tagQuestion')
    answers = request.POST.getlist('tagAnswer')
    dialogs = Dialog.objects.filter(user=lab_user).order_by('-log_time')
    pics = UserPic.objects.filter(user=lab_user, pic_type=picType['dialog'])
    user_answers = UserInfoA.objects.filter(user=lab_user, is_del=False)
    print('pic_name is-dialog is-ques is-answ:\t', pic_name, bool(dialog), bool(questions), bool(answers))
    if dialog:
        print('@添加沟通记录')
        user = request.user
        Dialog.objects.create(
            dialog=dialog,
            user=lab_user,
            recorder=user
        )
        dialogs = Dialog.objects.filter(user=lab_user).order_by('-log_time')
        print('dialog-len:\t', len(dialogs))
    print('---------------------')
    pic_form = ImgForm(request.POST, request.FILES)
    print('pic_form.is_valid():\t', pic_form.is_valid())
    if pic_form.is_valid():
        print('@添加图片')
        pic = pic_form.cleaned_data['pic']
        print('pic:\t', pic)
        image = Image.open(pic)
        print('image:\t', image)
        name = picType['dialog'] + '-' + lab_user.user.username + '-' + \
            datetime.datetime.now().strftime('%Y-%m-%d') + '.' + pic_name.split('.')[-1]
        image.save('media/img/gallery/%s' % name)
        pic_obj, _ = PicData.objects.get_or_create(pic=pic, defaults={
            'name': name
        })
        print('pic_obj:\t', pic_obj)
        UserPic.objects.create(
            user=lab_user,
            pic=pic_obj,
            pic_type=picType['dialog']
        )
        pics = UserPic.objects.filter(user=lab_user, pic_type=picType['dialog'])
        print('---------------------')
    if questions and answers:
        print('@修改资料')
        info = dict(zip(questions, answers))
        print('info:\t', info)
        for question in set(questions) & {attr.attr for attr in attr_option}:
            print('MODE: 已存在有选项的属性')
            attr = get_object_or_404(UserAttr, attr=question)
            print('question:\t', question)
            if info[question] not in [option.option for option in attr.options.all()]:
                print('mode: 保存新选项')
                print('new-question-option:\t', question, info[question])
                AttrOption.objects.create(
                    option=info[question],
                    attr=attr
                )

lab/labcrm/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap.min.css' %}" />
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap-theme.min.css' %}" />
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap-datetimepicker.min.css' %}" />
	{% block link %}<link />{% endblock %}
    <title>{% block title %}标题{% endblock %}</title>
</head>
<body class='container-fluid'>

<header class='row'>
	{% block header %}页眉{% endblock %}
</header>

{% block head_hr %}
<hr />
{% endblock %}

<content class='row'>
	{% block content %}内容{% endblock %}
</content>

<footer class='row'>
	{% block footer %}
		<p class='text-center'><b><a>***感谢访问***</a></b></p>
	{% endblock %}
</footer>

{% block modal %}{% endblock %}
<!--script src="http://code.jquery.com/jquery.js"></script-->
<script src="{% static 'bootstrap3\js\jquery.min.js' %}" charset="UTF-8"></script>
<script src="{% static 'bootstrap3\js\bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap3\js\npm.js' %}"></script>
<script src="{% static 'bootstrap3\js\moment.min.js' %}"></script>
<script src="{% static 'bootstrap3\js\bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script src="{% static 'bootstrap3\js\bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
function navbarLogin(){
	var para = document.getElementById('fromNavbar');
	para.onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest();
		xhr.open("POST", f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var rowNew = xhr.responseText;
				if(rowNew.length>0){
					para.innerHTML = rowNew;
				}else{
					alert('用户名或密码错误！');
				};
			};
		};
		xhr.send(formData);
	};
};

function h(e) {
	// textarea 高度自增长
	if(e.scrollHeight<80){
		$(e).css({'height':'auto','overflow-y':'hidden'}).height(84);
	}else{
		$(e).css({'height':'auto','overflow-y':'hidden'}).height(e.scrollHeight);
	};
};
$('textarea').each(function () {
	h(this);
}).on('input', function () {
	h(this);
});
</script>
{% block script %}{% endblock %}
</body>
</html>

lab/labcrm/templates/base2.html
{% extends 'base.html' %}
{% block header %}
{% block h1 %}{% endblock %}
<nav class="col-md-12 navbar navbar-default{% block topfix %} navbar-fixed-top{% endblock %}">
	<div class='container-fluid'>
		{% block homepage %}
		<p class='navbar-text navbar-center'><a class='navbar-link' href='{% url "homepage" %}'>crossin编程实战训练营</a></p>
		{% endblock %}
		{% block nav_bar %}
			{% include 'labcrm/tools/nav_bar.html' %}
		{% endblock  %}
		<form class="navbar-form navbar-right" action='{% url "accounts:login" %}' id='fromNavbar' method='POST'>
		{% csrf_token %}
		{% if user.is_authenticated %}
			<label>欢迎您：{{ user }}</label>
			<a class="btn btn-default" href='{% url "accounts:logout" %}'>登出</a>
		</form>
		{% else %}
			<div class="form-group">
				<input name='username' type="text" class="form-control" placeholder="用户名">
				<input name='password' type="password" class="form-control" placeholder="密码">
			</div>
			<button type="submit" class="btn btn-default" onclick='navbarLogin()'>登录</button>
		</form>
		{% endif %}
	</div>
</nav>
{% endblock %}
{% block content %}
{% block content_hr %}
<hr />
{% endblock %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-2" id="row-left">
			{% block row-left %}
			{% endblock %}
		</div>
		<div class="col-md-10" id="row-right">
			{% block row-right %}
			{% endblock %}
		</div>
	</div>
</div>
{% endblock %}