lab/lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='homepage'),
    url(r'^accounts/', include('account.urls', namespace='accounts')),
    url(r'^crm/', include('labcrm.urls', namespace='crm')),
    url(r'^webot/', include('webotconf.urls', namespace='webot')),
    url(r'^group/', include('group.urls', namespace='group')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/labcrm/urls.py
from django.conf.urls import url, include
from labcrm import views


ajax_urls = [
    url(r'^preview', views.ajax_conf_preview, name='preview'),
    # url(r'^modify', views.ajax_detail_modify, name='modify'),
    url(r'^add', views.ajax_conf_add, name='add'),
    url(r'^del', views.ajax_user_del, name='del'),
    url(r'^new', views.ajax_new_user, name='new')
]

modify_urls = [
    url(r'^schedule', views.modify_schedule, name='schedule')
]


urlpatterns = [
    url(r'^ajax/', include(ajax_urls, namespace='ajax')),
    url(r'^modify/', include(modify_urls, namespace='modify')),
    url(r'^users', views.user_list, name='list'),
    url(r'^userclass', views.user_class, name='userclass'),
    url(r'^detail/(?P<new_id>.*)$', views.user_detail, name='detail2'),
    url(r'^detail', views.user_detail, name='detail'),
    url(r'^papers', views.papers_create, name='papers'),
    url(r'^paper/(?P<data_key>\d*)$', views.paper_display, name='paper2'),
    url(r'^paper', views.paper_display, name='paper'),
    url(r'^conf', views.ques_conf, name='conf'),
    url(r'^fill/(?P<data_key>\d*)$', views.ques_fill, name='fill'),
    url(r'^fill', views.ques_fill, name='fill2'),
    url(r'^class', views.link_to_class, name='class'),
    url(r'^courses', views.learning_courses, name='courses'),
    url(r'^statistic', views.subject_statistic, name='statistic'),
    url(r'^schedule', views.schedule_statistic, name='schedule'),
]

lab/labcrm/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from group.models import StudentGroup

class LabUser(models.Model):
    """
    用户
    """
    # relate_name:让关联的对象反查到源对象
    # on_delete:models.CASCADE级联删除
    user = models.OneToOneField(User, verbose_name='用户', on_delete=models.CASCADE, related_name='labuser')
    nickname = models.CharField(max_length=30, verbose_name='用户名', null=True, blank=True)
    wechat = models.CharField(max_length=30, verbose_name='微信号', blank=True, null=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    class_id = models.IntegerField(verbose_name='教室ID', blank=True, null=True)
    # teach_assistance
    ta = models.CharField(max_length=30, verbose_name='助教', default='暂无')
    # json 格式可扩充字段，{course_id: status}
    # status ={1: 期中, 2: 期末, 3: 期中+期末}
    statistic = models.TextField(verbose_name='完课统计', default='{}')
    CLASS_CHOICES = (
        (0, '无'),
        (1, '基础班'),
        (2, '实战班'),
    )
    classification = models.IntegerField(verbose_name='学员类别', default=0, choices=CLASS_CHOICES)
    group = models.ForeignKey(to=StudentGroup, related_name="groupusers", blank=True, null=True)

    def __str__(self):
        return self.user.username


class Paper(models.Model):
    """
    问卷
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='papers', null=True, blank=True)
    create_time = models.DateTimeField(verbose_name='建表时间', auto_now_add=True)
    finished_time = models.DateTimeField(verbose_name='填写时间', null=True, blank=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    is_fill = models.BooleanField(verbose_name='是否填写', default=False)
    key = models.IntegerField(verbose_name='秘钥')
    data = models.TextField(verbose_name='问卷数据')
    mark = models.CharField(verbose_name='标记', max_length=50, default='默认')

    def __str__(self):
        if self.finished_time:
            name = self.mark + ' ' + self.finished_time.strftime('%Y-%m-%d')
        else:
            name = self.mark + ' ' + self.create_time.strftime('%Y-%m-%d')
        return name


class UserAttr(models.Model):
    """
    用户属性
    """
    attr = models.CharField(verbose_name='属性', max_length=255)
    is_option = models.BooleanField(verbose_name='是否提供选项', default=False)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.attr


class AttrOption(models.Model):
    """
    属性预选项
    """
    option = models.CharField(verbose_name='选项', max_length=255)
    attr = models.ForeignKey(UserAttr, verbose_name='属性', related_name='options')

    def __str__(self):
        return self.option


class UserInfoQ(models.Model):
    """
    用户属性提问
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='questions')
    paper = models.ForeignKey(Paper, verbose_name='问卷', related_name='questions', blank=True, null=True)
    attr = models.ForeignKey(UserAttr, verbose_name='属性', related_name='questions')
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.attr.attr


class UserInfoA(models.Model):
    """
    用户属性回答
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(UserInfoQ, verbose_name='问题', on_delete=models.CASCADE, related_name='answers')
    answer = models.CharField(verbose_name='回答', max_length=255)
    create_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.answer


class Dialog(models.Model):
    """
    对话记录
    """
    dialog = models.TextField(verbose_name='对话记录')
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='dialogs')
    recorder = models.ForeignKey(User, verbose_name='记录员')
    log_time = models.DateTimeField(verbose_name='记录时间', auto_now_add=True)

    def __str__(self):
        name = self.user.nickname + ' ' + self.log_time.strftime('%Y-%m-%d')
        return name


class PicData(models.Model):
    """
    图片数据
    """
    pic = models.ImageField(verbose_name='地址', upload_to='img/gallery', unique=True)
    create_time = models.DateTimeField(verbose_name='上传时间', auto_now_add=True)
    name = models.CharField(verbose_name='图片名', max_length=50)

    def __str__(self):
        return self.name


class UserPic(models.Model):
    """
    用户图片
    """
    pic = models.ForeignKey(PicData, verbose_name='图片', on_delete=models.CASCADE, related_name='upic')
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='upic')
    pic_type = models.CharField(verbose_name='图片类型', max_length=30, default='NoType')

    def __str__(self):
        return self.pic.name


class LearnedCourse(models.Model):
    """
    已学课程
    """
    # 利用选项设置 course_id 索引，查看课程方法 get_course_id_display()
    COURSE_CHOICES = (
        (0, '课外课程'),
        (1, 'Python 零基础入门'),
        (2, '爬虫实战'),
        (3, '开发训练营')
    )
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='courses')
    title = models.CharField(max_length=255, verbose_name='课程题目')
    learn_time = models.DateTimeField(verbose_name='学习时间')
    is_inner = models.BooleanField(verbose_name='内部课程', default=True)
    course_id = models.IntegerField(verbose_name='科目ID', default=0, choices=COURSE_CHOICES)

    def __str__(self):
        return self.title


class LearningSchedule(models.Model):
    """
    学习进度
    """
    COURSE_CHOICES = LearnedCourse.COURSE_CHOICES
    SCHEDULE_CHOICES = (
        (1, '入门'),
        (2, '基础'),
        (3, '项目')
    )
    course_id = models.IntegerField(verbose_name='科目ID', default=0, choices=COURSE_CHOICES)
    schedule = models.IntegerField(verbose_name='学习阶段', choices=SCHEDULE_CHOICES)
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='schedule')
    note = models.CharField(verbose_name='备注', max_length=255)

    def __str__(self):
        return '{name} - {course}'.format(name=self.user.nickname, course=dict(self.COURSE_CHOICES)[self.course_id])

# GENDER_CHOICES = (
#     ('S', '保密'),
#     ('M', '男'),
#     ('F', '女'),
# )
# AGE_CHOICES = (
#     ('S', '保密'),  # Secret
#     ('C', '童年'),  # Childhood
#     ('J', '少年'),  # Juvenile
#     ('P', '青年'),  # Puberty
#     ('P', '壮年'),  # Prime of life
#     ('M', '中年'),  # Middle-aged
#     ('O', '老年'),  # Old Age
# )
# age = models.CharField(max_length=2, default='S', choices=AGE_CHOICES)
# gender = models.CharField(max_length=2, default='S', choices=GENDER_CHOICES)
# etc = models.TextField()

lab/labcrm/templates/labcrm/course_statistic.html
{% extends 'base2.html' %}
{% block title %}完课统计{% endblock %}
{% block nav_bar %}
	{% include 'labcrm/tools/nav_bar.html' with tag_statis="active" %}
{% endblock %}
{% block row-left %}
<a class='btn btn-lg btn-block {% block schedule_class %}btn-info{% endblock %}' href='{% url "crm:schedule" %}'>总体进度</a>
<hr />
<ul class="nav nav-pills nav-stacked nav-stacked text-center">
{% for c in course_list %}
	<li role="presentation" class="nav {% if course_id == c.index %}active{% endif %}"><a href='{% url "crm:statistic" %}?course={{ c.index }}'>{{ c.course }}</a></li>
{% endfor %}
</ul>
{% endblock %}
{% block row-right %}
<table class="table table-hover table-striped table-bordered">
	<caption><h3 class='text-center'>{{ course }}<h3></caption>
		<thead class='thead-inverse'>
		<tr>
			<th>学员</th>
			<th>课程总数</th>
			<th>最大课程进度</th>
			<th>最后学习时间</th>
			<th>期中项目</th>
			<th>期末项目</th>
			<th>学员所属群组</th>
		</tr>
		</thead>
	<tbody id='courseList'>
	{% for cd in course_data %}
		<tr class='{% if cd.mid and cd.end %}success{% endif %}'>
			<td><a href='{% url "crm:courses" %}?uid={{ cd.user.id }}'>{{ cd.user }}</a></td>
			<td>{{ cd.amounts }}</td>
			<td>{{ cd.max }}</td>
			<td>{{ cd.latest|date:"Y-m-d" }}</td>
			{% if cd.mid %}
				<td><strong class='text-danger'>{{ cd.mid }}</strong></td>
			{% else %}
				<td>{{ cd.mid }}</td>
			{% endif %}
			{% if cd.end %}
				<td><strong class='text-danger'>{{ cd.end }}</strong></td>
			{% else %}
				<td>{{ cd.end }}</td>
			{% endif %}
			<td>{{ cd.user.group.group_name }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

lab/labcrm/templates/labcrm/courses.html
{% extends 'base2.html' %}
{% block title %}学习记录{% endblock %}
{% block row-left %}
<button id='btncourseAdd' class='btn btn-info btn-block btn-lg' data-toggle="modal" data-target="#courseModal">添加课程</button>
{% endblock %}
{% block row-right %}
<table class="table table-hover table-striped table-bordered">
	<caption class='text-center'><h3><a href='{% url "crm:detail" %}?uid={{ lab_user.id }}'>{{ lab_user }}</a></a></h3></caption>
	<thead class='thead-inverse'>
	<tr>
		<th class='col-lg-1'>序号</th>
		<th class='col-lg-8'>课程标题</th>
		<th class='col-lg-2'>学习时间</th>
		<th class='col-lg-1'>内部课程</th>
	</tr>
	</thead>
	<tbody id='courseList'>
	{% for course in courses %}
		<tr {% if not course.is_inner %}class='warning'{% endif %}>
			{% include 'labcrm/ajax/course_list.html' %}
		</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}
{% block modal %}
<div class="modal fade" id='courseModal' tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">添加课程：</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal" id='formCourse' action='' method='POST'>
					{% csrf_token %}
					<div class="form-group">
						<label class='col-md-2 control-label' for='courseName'>课程名：</label>
						<div class='col-md-10'>
							<input id='courseName' class='form-control' name='courseTitle' onfocus="this.select()" placeholder='课程名'>
						</div>
					</div>
					<div class="form-group">
						<label for="dtp_input" class="col-md-2 control-label">日期：</label>
						<div class='col-md-10'>
							<div class="input-group date form_datetime">
								<input name='courseTime' class="form-control" type="text" readonly placeholder='学习日期'>
								<span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
								<span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label class='col-md-2 control-label' for='is_inner'>站内课：</label>
						<div class='col-md-10'>
							<input id='is_inner' class='form-control' disabled value='False'>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id='btn-modal-hide' data-dismiss="modal">取消</button>
				<button type="submit" class="btn btn-primary" form='formCourse' onclick='courseAddSure()'>添加</button>
			</div>										
		</div>
	</div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
$('.form_datetime').datetimepicker({
	language: 'zh-CN',
	format: "yyyy-mm-dd",
	weekStart: 1,
	todayBtn:  1,
	autoclose: 1,
	todayHighlight: 1,
	startView: 2,
	minView: 2,
	forceParse: 0,
	showMeridian: 1
});

$('#courseModal').on('hidden.bs.modal', function (e) {
	// 重置模态框数据及格式
	document.getElementById('formCourse').reset();
});

function courseAddSure(){
	// 添加课程确认
	console.log('添加课程确认');
	document.getElementById('formCourse').onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest(),
			para = document.getElementById('courseList').insertRow(0);
		xhr.open('POST', f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				console.log(para);
				para.setAttribute('class', 'warning');
				para.innerHTML = xhr.responseText;
				para.getElementsByClassName('newIndex')[0].innerText = parseInt(para.nextElementSibling.firstElementChild.innerText)+1;
			};
		};
		xhr.send(formData);
		$('#courseModal').modal('hide');
	};
};
</script>
{% endblock %}

lab/labcrm/templates/labcrm/paper_display.html
{% extends 'base.html' %}
{% block title %}问卷预览{% endblock %}
{% block header %}
	<h1 class='text-center'><a href=''>crossin编程实战训练营</a></h1>
{% endblock %}
{% block head_hr %}{% endblock %}
{% block content %}
<div class='col-md-12'>
	<form>
		<h3 class='text text-center'>{{ title }}</h3>
		<p class='text text-right'><em><b>TO -- </b></em><span id='username'>{{ labUser }}</span></p>
		<p class='text'>{{ paper_desc }}</p>
		{% for ques in questions %}
		<hr />
		<div class='row'>
			<div class="form-group has-success col-lg-12">
				<label class="col-lg-2 text-center" for='labUser{{ ques.aid }}'>{{ ques.desc }}</label>
				<div class='col-lg-10'>
				{% if ques.attr.is_option %}
					{% for option in ques.attr.options.all %}
					<div class='radio' id='labUser{{ ques.aid }}'>
						<label>
						{% if option.option == ques.value %}
							<input type="radio" value="{{ option.option }}" checked disabled>
						{% else %}
							<input type="radio" value="{{ option.option }}" disabled>
						{% endif %}
							{{ option.option }}
						</label>
					</div>
					{% endfor %}
				{% else %}
					<input type='text' id='labUser{{ ques.aid }}' class="form-control" placeholder='请填写' value='{{ ques.value }}' disabled>
				{% endif %}
				</div>
			</div>
		</div>
		{% endfor %}
	</form>
</div>
{% endblock %}
{% block footer %}
<p class='text-center'><b><a>***感谢访问***</a></b></p>
<hr />
<hr />
{% endblock %}
{% block modal %}
{% if user.is_staff and not modal_display %}
<div class='row'>
	<nav class="col-md-12 navbar navbar-default navbar-fixed-bottom">
		<div class='container-fluid'>
			<p class='navbar-text navbar-left'><b>管理员菜单</b></p>
			<p class='navbar-text navbar-left'><label>欢迎您：{{ user }}</label></p>
			<p class='navbar-text navbar-center'><a class='navbar-link' href='{% url "homepage" %}'>crossin编程实战训练营</a></p>
			{% include 'labcrm/tools/nav_bar.html' %}
			<form class='navbar-form navbar-right'>
			{% if paper.user %}
				<a tabindex="0" class="btn close pull-left" aria-label="Close" role="button" data-toggle="popover" data-placement="top" data-trigger="focus"  data-content="无法重命名非模板问卷" disabled>
					<span aria-hidden="true" style='font-size:0.6em'>{{ paper }}</span>
				</a>
			{% else %}
				<a class='btn' id='navName' onclick='reName()'>{{ paper }}</a>
				<input class='hidden' id='navMark' placeholder='{{ paper.mark }}' value='{{ paper.mark }}' onfocus='this.select()' onblur='reNameSure()'>
				<span class='hidden' id='navTime'>{{ paper.create_time|date:"Y-m-d" }}</span>
			{% endif %}
			{% if not filled %}
				{% if labUser %}
				<a class="btn btn-success" href='{% url "crm:fill2" %}/{{ data_key }}'>生成问卷</a>
				{% else %}
				<a class="btn btn-success" data-toggle="modal" data-target="#userListModal">生成问卷</a>
				{% endif %}
			{% endif %}
			</form>
		</div>
	</nav>
</div>
{% if not labUser %}
<div class="modal fade" id='userListModal' tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">生成问卷：</h4>
			</div>
			<div class="modal-body">
				<form id='formPaperCre' method='POST' action='{% url "crm:papers" %}'>
				{% csrf_token %}
				<input class='hidden' name='data_key' value='{{ data_key }}'>
				<table class="table table-hover table-striped table-bordered">
					<caption>
						<b>成员列表</b>
						<button class='pull-right btn btn-primary' form='' onclick='addNew()'>新成员</button>
					</caption>
					<thead class='thead-inverse'>
						<tr id='tr_papers'>
							<th>昵称</th><!-- 昵称为本站 user.username -->
							<th>微信</th>
							<th>助教</th>
							<th>问卷</th>
							<th>入学日期</th>
							<th>沟通记录</th>
							<th>新问卷</th>
						</tr>
					</thead>
					<tbody id='userList'>
					{% include 'labcrm/ajax/user_del.html' %}
					</tbody>
				</table>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id='btn-modal-hide' data-dismiss="modal">取消</button>
				<button type="submit" class="btn btn-success" id='btnCreate' form='formPaperCre'>生成</button>
			</div>										
		</div>
	</div>
</div>
{% endif %}
{% endif %}
{% endblock %}
{% block script %}
<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})

function addNew(){
	// 添加新成员
	var newRow = document.getElementById('userList').insertRow(0),
		tr_papers = document.getElementById('tr_papers'),
		btnCreate = document.getElementById('btnCreate'),
		th_papers = document.getElementsByTagName('th');
	// console.log(th_papers, th_papers.length);
	for(var i=0;i<th_papers.length-1;i++){
		var cell = newRow.insertCell();
		cell.innerHTML = '<td><input class="form-control" disabled placeholder="' + th_papers[i].innerText + '"></td>';
		// console.log(cell);
	};
	newRow.insertCell().innerHTML = '<td><input type="checkbox" name="userId" checked disabled></td>';
	newRow.firstElementChild.firstElementChild.setAttribute('name', 'nickname');
	newRow.firstElementChild.firstElementChild.setAttribute('onblur', 'addNewSrue(this)');
	newRow.firstElementChild.firstElementChild.removeAttribute('disabled');
	newRow.setAttribute('class', 'success');
	newRow.children[0].children[0].focus();
	btnCreate.setAttribute('disabled', true);
};

function addNewSrue(e){
	// 添加新成员确认
	var btnCreate = document.getElementById('btnCreate');
	if(e.value.length > 0){					// 后台判断是否为空 TODO
		var xhr = new XMLHttpRequest();
		xhr.open("GET", '{% url "crm:ajax:new" %}?nickname=' + e.value, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				if(xhr.responseText.length > 0){
					var uid = xhr.responseText,
						td = e.parentElement,
						checkbox = td.parentElement.children[td.parentElement.childElementCount - 1].children[0],
						tds = td.parentElement.getElementsByTagName('td');
					console.log(tds.length);
					for(var i=1;i<tds.length-1;i++){
						console.log(11111, tds[i].firstElementChild.getAttribute('placeholder'));
						tds[i].innerText = tds[i].firstElementChild.getAttribute('placeholder');
					};
					td.innerHTML = '<a href=\'{% url "crm:detail" %}?uid=' + uid + "'>" + e.value + '</a>';
					checkbox.value = uid;
					checkbox.removeAttribute('disabled');
					btnCreate.removeAttribute('disabled');
				}else{
					alert('用户名重复');
					e.select();
				};
			};
		};
		xhr.send();
	}else{
		var tr = e.parentElement.parentElement;
		tr.parentElement.removeChild(tr);
		btnCreate.removeAttribute('disabled');
	};
};

function reName(){
	var navMark = document.getElementById('navMark'),
		navName = document.getElementById('navName'),
		navTime = document.getElementById('navTime');
	navName.className = 'hidden';
	navMark.className = 'form-control';
	navTime.className = 'text-primary';
	navMark.focus();
};

function reNameSure(){
	var xhr = new XMLHttpRequest(),
		navMark = document.getElementById('navMark'),
		navName = document.getElementById('navName'),
		navTime = document.getElementById('navTime');
	xhr.open("GET", '?reName=' + navMark.value, true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			navTime.className = 'hidden';
			navMark.className = 'hidden';
			navName.className = 'btn';
			navName.innerText = xhr.responseText;
		};
	};
	xhr.send();
};
</script>
{% endblock %}
</body>
</html>

lab/labcrm/templates/labcrm/paper_list.html
{% extends 'base2.html' %}
{% block title %}问卷列表{% endblock %}
{% block quesConf %}active{% endblock %}
{% block row-left %}
<ul class="nav nav-pills nav-stacked nav-stacked text-center">
	<!--li role="presentation" class="nav {% if PType == 'M' %}active{% endif %}"><a href='#' onclick='linkTurn("M")'>问卷模版</a></li-->
	<li role="presentation" class="nav {% if PType == 'M' %}active{% endif %}"><a href='?PType=M'>问卷模版</a></li>
	<li role="presentation" class="nav {% if PType == 'TF' %}active{% endif %}"><a href='?PType=TF'>未填问卷</a></li>
	<li role="presentation" class="nav {% if PType == 'F' %}active{% endif %}"><a href='?PType=F'>已填问卷</a></li>
	<li role="presentation" class="nav {% if PType == 'A' %}active{% endif %}"><a href='?PType=A'>全部问卷</a></li>
	<li role="presentation" class="nav {% if PType != 'N' %}hidden{% endif %} active"><a href='#'>新建问卷</a></li>
</ul>
{% endblock %}
{% block row-right %}
<table class="table table-hover table-striped table-bordered">
	<caption class='text-center'><h2>问卷列表</h2></caption>
		<thead class='thead-inverse'>
		<tr>
			<th class='text-center'>问卷名</th>
			{% if PType != 'M' %}
			<th class='text-center'>调查对象</th>
			{% endif %}
			<th class='text-center'>创建时间</th>
			{% if PType == 'A' or PType == 'F' %}
			<th class='text-center'>填写时间</th>
			{% endif %}
			<th class='col-lg-1 text-center'>删除</th>
		</tr>
		</thead>
	<tbody id='userList'>
	{% include 'labcrm/ajax/papers.html' %}
	</tbody>
</table>
{% endblock %}
{% block script %}
<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})

function paperDel(pid){
	var trDel = document.getElementById('paper'+pid),
		xhr = new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			if(xhr.responseText=='T'){
				trDel.parentElement.removeChild(trDel);
			};
		};
	};
	xhr.open("GET", '?paperDel='+pid, true);
	xhr.send();
};
/*
function linkTurn(type){
	var para = document.getElementById('userList'),
		xhr = new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			para.innerHTML = xhr.responseText;
		};
	};
	xhr.open("GET", '{% url "crm:papers" %}?PType='+type, true);
	xhr.send();
}
*/
</script>
{% endblock %}

lab/labcrm/templates/labcrm/ques_data.html
<div class='hidden'>
	<form action='' method='POST' id='quesCre'>
	{% csrf_token %}
		<input name='is_cre' value=true>
		<input name='paper_title' value='{{ title }}'>
		<input name='labUser' value='{{ labUser }}'>
		<input name='paper_desc' value='{{ paper_desc }}'>
		<input class='hidden' name='mark' value='{{ mark }}'>
		{% for ques in questions2 %}
			<input name='ques_desc' value='{{ ques.desc }}'>
			<input name='attr_id' value='{{ ques.aid }}'>
		{% endfor %}
	</form>
</div>

lab/labcrm/templates/labcrm/schedule_statistic.html
{% extends 'labcrm/course_statistic.html' %}
{% block schedule_class %}btn-primary{% endblock %}
{% block row-right %}
<table class="table table-hover table-striped table-bordered">
	<caption><h3 class='text-center'>总体进度<h3></caption>
		<thead class='thead-inverse'>
		<tr>
			<th>学员</th>
			<th>课程</th>
			<th>阶段</th>
			<th>备注</th>
		</tr>
		</thead>
	<tbody id='courseList'>
	{% for schedule in schedules %}
		<tr>
			<td><a href='{% url "crm:courses" %}?uid={{ schedule.user.id }}'>{{ schedule.user }}</a></td>
			<td>{{ schedule.get_course_id_display }}</td>
			<td>{{ schedule.get_schedule_display }}</td>
			<td>{{ schedule.note }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}