lab/lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='homepage'),
    url(r'^accounts/', include('account.urls', namespace='accounts')),
    url(r'^crm/', include('labcrm.urls', namespace='crm')),
    url(r'^webot/', include('webotconf.urls', namespace='webot')),
    url(r'^group/', include('group.urls', namespace='group')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/webotconf/urls.py
from django.conf.urls import url, include
from . import views

ajax_patterns = [
    url(r'^modify', views.ajax_conf_modify, name='modify'),
]

urlpatterns = [
    url(r'^ajax/', include(ajax_patterns, namespace='ajax')),
    url(r'^rule', views.rule_conf, name='rule'),
    url(r'^qas', views.qa_conf_strict, name='qas'),
    url(r'^qa', views.qa_conf, name='qa'),
    url(r'^pic', views.pic_subject, name='pic'),
]

lab/webotconf/models.py
from django.db import models

# Create your models here.


class ChatRoom(models.Model):
    nickname = models.CharField(verbose_name='群名', max_length=50)
    order = models.IntegerField(verbose_name='优先级', unique=True)

    def __str__(self):
        return self.nickname


class RuleAddFriend(models.Model):
    keyword = models.CharField(verbose_name='关键字', max_length=20)
    chatroom = models.ForeignKey(ChatRoom, verbose_name='群', on_delete=models.CASCADE, related_name='rules')

    def __str__(self):
        return self.keyword + '-' + self.chatroom.nickname


class QAKeyWord(models.Model):
    keyword = models.CharField(verbose_name='关键字', max_length=20)
    is_strict = models.BooleanField(verbose_name='是否严格', default=False)

    def __str__(self):
        return self.keyword


class QAReply(models.Model):
    desc = models.CharField(verbose_name='描述', max_length=30, blank=True, null=True)
    is_pic = models.BooleanField(verbose_name='是否图片', default=False)
    reply_text = models.TextField(verbose_name='回答', blank=True, null=True)
    reply_pic = models.ImageField(verbose_name='图片回答', upload_to='img/answers', blank=True, null=True)
    keywords = models.ManyToManyField(QAKeyWord, verbose_name='关键字集', related_name='replies')

    def __str__(self):
        if self.desc:
            return self.desc
        else:
            name = 'R:' + '-'.join([keyword.keyword for keyword in self.keywords])


class PicSubject(models.Model):
    tag = models.CharField(verbose_name='活动标签', max_length=30)
    reply = models.TextField(verbose_name='回复')
    time_on = models.DateTimeField(verbose_name='开始时间', auto_now_add=True)
    time_off = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)
    is_underway = models.BooleanField(verbose_name='进行中', default=True)

    def __str__(self):
        return self.tag


class SubjectMember(models.Model):
    subject = models.ForeignKey(PicSubject, verbose_name='活动', on_delete=models.CASCADE, related_name='members')
    nickname = models.CharField(verbose_name='昵称', max_length=30)

    def __str__(self):
        return self.subject.tag + '-' + self.nickname

lab/webotconf/views.py
from django.shortcuts import render, get_object_or_404
# from .models import ChatRoom, RuleAddFriend
from .models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from PIL import Image
import re
from labcrm.views import ImgForm
import datetime
# Create your views here.


@login_required
def rule_conf(request):
    if request.method == 'POST':
        is_strict = request.POST.get('is_strict')
        list_keywords = request.POST.getlist('keywords')
        if is_strict == 'True':
            list_orders = [int(order) + 100 for order in request.POST.getlist('orders')]
            list_room = ['#' + room for room in request.POST.getlist('rooms')]
        else:
            list_orders = request.POST.getlist('orders')
            list_room = request.POST.getlist('rooms')
        rules = zip(list_room, list_orders, list_keywords)
        print(len(list_keywords), len(list_orders), len(list_room))
        if len(set(list_room)) < len(list_room):
            return HttpResponse()
        for rule in rules:
            keywords = re.split(r'[,，;；.。| +-]+', rule[2].strip(',，;；.。| +-'))
            print(rule, keywords)
            room, _ = ChatRoom.objects.update_or_create(nickname=rule[0], defaults={
                'order': rule[1]
            })
            for keyword in keywords:
                RuleAddFriend.objects.get_or_create(
                    keyword=keyword,
                    chatroom=room
                )
        if is_strict == 'True':
            rooms = ChatRoom.objects.all().filter(order__gt=100).order_by('order')
        else:
            rooms = ChatRoom.objects.all().filter(order__lt=100).order_by('order')
        return HttpResponse(render(request, 'webotconf/ajax/rules.html', {
            'rooms': rooms,
            'is_strict': is_strict
        }))
    elif request.GET.get('strict'):
        rooms = ChatRoom.objects.all().filter(order__gt=100).order_by('order')
        is_strict = 'True'
    else:
        rooms = ChatRoom.objects.all().filter(order__lt=100).order_by('order')
        is_strict = 'False'
    return render(request, 'webotconf/webot.html', {
        'rooms': rooms,
        'is_strict': is_strict
    })


@login_required
def qa_conf_strict(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        desc = request.POST.get('desc')
        answer = request.POST.get('answer')
        is_modify = request.POST.get('modify')
        print('keyword: ', keyword)
        print('desc: ', desc)
        print('answer: ', answer)
        print('is_modify: ', is_modify)
        qa_keyword, is_new = QAKeyWord.objects.get_or_create(keyword=keyword, is_strict=True)
        form_data = ImgForm(request.POST, request.FILES)
        if is_modify:
            qa_keyword = get_object_or_404(QAKeyWord, keyword=keyword, is_strict=True)
            qa_reply = get_object_or_404(QAReply, keywords=qa_keyword)
            qa_reply.desc = desc
            qa_reply.reply_text = answer
            # qa_reply.save()
            # return HttpResponse(render(request, 'webotconf/ajax/qa_group.html', {
            #     'keyword': qa_keyword,
            # }))
        elif is_new:
            qa_reply = QAReply.objects.create(
                desc=desc,
                reply_text=answer,
            )
            qa_reply.keywords.add(qa_keyword)
        else:
            return HttpResponse()
        if form_data.is_valid():
            pic = form_data.cleaned_data['pic']
            qa_reply.reply_pic = pic
            qa_reply.is_pic = True
        qa_reply.save()
        return HttpResponse(render(request, 'webotconf/ajax/qa_group.html', {
            'keyword': qa_keyword,
        }))
    delete_kid = request.GET.get('delete')
    print('delete_kid: ', delete_kid)
    if delete_kid:
        qa_keyword = get_object_or_404(QAKeyWord, id=delete_kid)
        qa_reply = get_object_or_404(QAReply, keywords=qa_keyword)
        qa_keyword.delete()
        qa_reply.delete()
        return HttpResponse()
    keywords = QAKeyWord.objects.filter(is_strict=True).order_by('keyword')
    return render(request, 'webotconf/qa_conf.html', {
        'keywords': keywords,
        'is_strict_qa': 'True'
    })


@login_required
def qa_conf(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        desc = request.POST.get('desc')
        answer = request.POST.get('answer')
        is_modify = request.POST.get('modify')
        print('keyword: ', keyword)
        print('desc: ', desc)
        print('answer: ', answer)
        print('is_modify: ', is_modify)
    keywords = QAKeyWord.objects.filter(is_strict=False)
    return render(request, 'webotconf/qa_conf.html', {
        'keywords': keywords,
        'is_strict_qa': 'False'
    })


@login_required
def pic_subject(request):
    sid = request.GET.get('close')
    rid = request.GET.get('reSub')
    if sid:
        print('sid: ', sid)
        subject = get_object_or_404(PicSubject, id=sid)
        subject.is_underway = False
        subject.time_off = datetime.datetime.now()
        subject.save()
        print('subject: ', subject, subject.is_underway, subject.time_off)
        return HttpResponse(render(request, 'webotconf/ajax/sub_history.html', {
            'subjectHis': subject
        }))
    elif request.method == 'POST':
        tag = request.POST.get('tag')
        reply = request.POST.get('reply')
        subject = PicSubject.objects.create(
            tag=tag,
            reply=reply,
            time_on=datetime.datetime.now()
        )
        return HttpResponse(render(request, 'webotconf/ajax/sub_underway.html', {
            'subject': subject
        }))
    elif rid:
        subject = get_object_or_404(PicSubject, id=rid)
        subject.is_underway = True
        subject.save()
        return HttpResponse(render(request, 'webotconf/ajax/sub_underway.html', {
            'subject': subject
        }))
    subject = PicSubject.objects.filter(is_underway=True).last()
    subject_history = PicSubject.objects.filter(is_underway=False)
    return render(request, 'webotconf/pic_subject.html', {
        'is_pic': True,
        'subject': subject,
        'subject_history': subject_history
    })


@login_required
def ajax_conf_modify(request):
    is_strict = request.GET.get('strict')
    print('is_strict: ', is_strict, type(is_strict), is_strict==False)
    if is_strict == 'True':
        rooms = ChatRoom.objects.all().filter(order__gt=100).order_by('order')
    else:
        rooms = ChatRoom.objects.all().filter(order__lt=100).order_by('order')
    return HttpResponse(render(request, 'webotconf/ajax/modify.html', {
        'rooms': rooms,
        'is_strict': is_strict
    }))

lab/webotconf/templates/webotconf/pic_subject.html
{% extends 'webotconf/webot.html' %}
{% block buttons %}

{% endblock %}
{% block row-right %}
<div class='jumbotron' id='subUnderway'>
{% if subject %}
	{% include 'webotconf/ajax/sub_underway.html' %}
{% else %}
	{% include 'webotconf/ajax/sub_create.html' %}
{% endif %}
</div>
<hr />
<div class='row'>
	<h3>
		<label>历史活动</label>
		<span class='pull-right' id='subCount'>{{ subject_history.count }}</span>
		<span class='pull-right'>活动总数：</span>
	</h3>
	<hr />
	<div id="accordionSub" role="tablist" aria-multiselectable="true">
	{% for subjectHis in subject_history %}
		<div class="panel panel-default" id='subHistory{{ subjectHis.id }}'>
			{% include 'webotconf/ajax/sub_history.html' %}
		</div>
	{% endfor %}
	</div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id='subCreModal' tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">开启新活动：</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal" id='formSubCre' action='' method='POST'>
					{% csrf_token %}
					<div class='form-group'>
						<label class='control-label col-lg-1' for='subTag'>标签</label>
						<div class='col-lg-10'>
							<input class='form-control' name='tag' id='subTag' placeholder='标签' onfocus="this.select()" required=true>
						</div>
					</div>
					<div class='form-group'>
						<label class='control-label col-lg-1' for='subReply'>回复</label>
						<div class='col-lg-10'>
							<textarea class='form-control' name='reply' id='subReply' placeholder='回复' onfocus="this.select()" required=true rows=3></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id='btn-modal-hide' data-dismiss="modal">取消</button>
				<button type="submit" class="btn btn-primary" form='formSubCre' onclick='subCreate()'>开启</button>
			</div>										
		</div>
	</div>
</div>
{% endblock %}
{% block script %}
<script>
function reSubBtnSwith(wake_it){
	var reSubBtns = document.getElementsByClassName('reSubBtn')
	if(wake_it){
		for(var i=0;i<reSubBtns.length;i++){
			reSubBtns[i].removeAttribute('disabled');
		};
	}else{
		for(var i=0;i<reSubBtns.length;i++){
			reSubBtns[i].setAttribute('disabled', true);
		};
	};
};
function subClose(sid){
	var xhr = new XMLHttpRequest(),
		para = document.getElementById('accordionSub'),
		newDiv = document.createElement('div'),
		subCount = document.getElementById('subCount'),
		subUnderway = document.getElementById('subUnderway');
	para.insertAdjacentElement('afterbegin', newDiv);
	newDiv.setAttribute('class', 'panel panel-default');
	newDiv.setAttribute('id', 'subHistory'+sid);
	xhr.open('GET', '?close='+sid, true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			newDiv.innerHTML = xhr.responseText;
			subCount.innerHTML = Number(subCount.innerHTML) + 1;
			subUnderway.innerHTML = `{% include "webotconf/ajax/sub_create.html" %}`;
			reSubBtnSwith(true);
		};
	};
	xhr.send();
};

function subCreate(){
	document.getElementById("formSubCre").onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest(),
			para = document.getElementById('subUnderway');
		$('#subCreModal').modal('hide');
		xhr.open("POST", f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var rowNew = xhr.responseText;
				para.innerHTML = rowNew;
				reSubBtnSwith(false);
			};
		};
		xhr.send(formData);
	};
};

function reSub(sid){
	var xhr = new XMLHttpRequest(),
		para = document.getElementById('subUnderway'),
		subHistory = document.getElementById('subHistory'+sid),
		subCount = document.getElementById('subCount');
	xhr.open('GET', '?reSub='+sid, true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			para.innerHTML = xhr.responseText;
			subCount.innerHTML = Number(subCount.innerHTML) - 1;
			subHistory.parentElement.removeChild(subHistory);
			reSubBtnSwith(false);
		};
	};
	xhr.send();
}
</script>
{% endblock %}

lab/webotconf/templates/webotconf/qa_conf.html
{% extends 'webotconf/webot.html' %}
{% block buttons %}
<button type="button" id='btnkw' class="btn btn-info btn-lg btn-block unhid hidSwith" onclick='kwAdd(this)'>增加关键字</button>
{% endblock %}
{% block row-right %}
{% if is_strict_qa == 'True' %}
<h3 class='text text-center'>严格问答配置</h3>
{% else %}
<h3 class='text text-center'>宽松问答配置</h3>
{% endif %}
<div id='qa_list'>
	{% for keyword in keywords %}
		{% include 'webotconf/ajax/qa_group.html' %}
	{% endfor %}
</div>
{% endblock %}
{% block script %}
<script>
var kw = desc = answ = '';

function kwAdd(e){
	// 新增关键字
	e.setAttribute('disabled', true);
	var para = document.getElementById("qa_list"),
		newForm = document.createElement("form");
	para.insertBefore(newForm, para.firstElementChild);
	newForm.setAttribute('id', 'newForm');
	newForm.setAttribute('class', 'form-horizontal has-success');
	newForm.innerHTML = '\
	<hr />' + "{% csrf_token %}" + '\
	<div class="form-group">\
		<label class="control-label col-lg-1" for="kw00">关键字：</label>\
		<div class="col-lg-3">\
			<input type="text" id="kw00" class="form-control inputs" name="keyword" onfocus="select()" placeholder="关键字" required>\
		</div>\
		<button class="pull-right btn btn-success" form="newForm" type="submit" onclick="QASave()">保存</button>\
		<button class="pull-right btn btn-danger" form="" onclick="QACancel()">取消</button>\
	</div>\
	<div class="form-group">\
		<label class="control-label col-lg-1" for="desc00">描述：</label>\
		<div class="col-lg-11">\
			<input type="text" id="desc00" class="form-control inputs" name="desc" onfocus="select()" placeholder="描述" required>\
		</div>\
	</div>\
	<div class="form-group">\
		<label class="control-label col-lg-1" for="answ00">回答：</label>\
		<div class="col-lg-11">\
			<textarea id="answ00" class="form-control inputs" name="answer" onfocus="select()" placeholder="回答" required rows=3></textarea>\
			<div class="input-group" id="picDiv">\
				<span class="input-group-addon" id="addonPic"><label for="inpPic" class="glyphicon glyphicon-cloud-upload"></label></span>\
				<input type="text" class="form-control" id="inpPicShow" placeholder="上传图片" aria-describedby="addonPic" name="pic_name">\
				<input type="file" class="btn btn-md btn-block" name="pic" id="inpPic" accept="image/*" style="display:none">\
			</div>\
		</div>\
	</div>'
	
	$('textarea').each(function () {
		h(this);
	}).on('input', function () {
		h(this);
	});
	
	var inpPic = document.getElementById('inpPic'),
	inpPicShow = document.getElementById('inpPicShow');
	inpPic.onchange = function(){
		inpPicShow.value=inpPic.value;
	};
	inpPicShow.onfocus = function(){
		inpPic.click();
		document.getElementById('answ00').focus();
	};
};

function QACancel(){
	// 取消新增
	var newFormCancel = document.getElementById('newForm');
	newFormCancel.parentNode.removeChild(newFormCancel);
	document.getElementById('btnkw').removeAttribute('disabled');
};

function QASave(){
	// 新关键字保存
	document.getElementById('newForm').onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			para = document.getElementById("qa_list"),
			newForm = document.createElement('form'),
			xhr = new XMLHttpRequest();
		para.insertBefore(newForm, para.firstElementChild);
		newForm.setAttribute('class', 'form-horizontal has-success');
		xhr.open("POST", '', true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var rowNew = xhr.responseText;
				if(rowNew){
					QACancel();
					newForm.innerHTML = rowNew.split('#js_split#')[2];
					newForm.setAttribute('id', 'form'+rowNew.split('#js_split#')[1]);
				}else{
					alert('关键字重复！');
				};
			};
		};
		xhr.send(formData);
	};
};

function QASwith(id){
	// 样式控制转换
	var btns = document.getElementsByClassName("btn"+id),
		inps = document.getElementsByClassName("inp"+id),
		mods = document.getElementsByClassName('modify');
	for(var i=0;i<btns.length;i++){
		// 问答组按钮转换
		var classVal = btns[i].getAttribute("class");
		if(classVal.match('hidden')){
			classVal = classVal.replace('hidden', 'unhid');
		}else{
			classVal = classVal.replace('unhid', 'hidden');
		};
		btns[i].setAttribute("class", classVal);
	};
	for(var i=0;i<inps.length;i++){
		// 输入控件转换
		if(inps[i].getAttribute('readonly')){
			inps[i].removeAttribute('readonly');
		}else{
			inps[i].setAttribute('readonly', true);
		};
	};
	for(var i=0;i<mods.length;i++){
		// 修改按钮转换
		if(mods[i].getAttribute('disabled')){
			mods[i].removeAttribute('disabled');
		}else{
			mods[i].setAttribute('disabled', true);
		};
	};
};

function QAModify(id){
	// 关键字修改
	kw = document.getElementById('kw'+id).value;
	desc = document.getElementById('desc'+id).value;
	answ = document.getElementById('answ'+id).value;
	QASwith(id);
	
	var inpPic = document.getElementById('inpPic'+id),
	inpPicShow = document.getElementById('inpPicShow'+id);
	inpPic.onchange = function(){
		inpPicShow.value=inpPic.value;
	};
	inpPicShow.onfocus = function(){
		inpPic.click();
		document.getElementById('answ'+id).focus();
	};
};

function modifyCancel(id){
	// 关键字修改取消
	document.getElementById('kw'+id).value = kw;
	document.getElementById('desc'+id).value = desc;
	document.getElementById('answ'+id).value = answ;
	QASwith(id);
	kw = desc = answ = '';
};

function modifySure(id){
	// 关键字修改保存
	var para = document.getElementById('form'+id);
	para.onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest();
		xhr.open('POST', '', true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var rowNew = xhr.responseText;
				//if(rowNew){
					//QASwith();
					//para.innerHTML = rowNew.split('#js_split#')[2];
				//}else{
					//alert('关键字重复！');
				//};
				QASwith();
				para.innerHTML = rowNew.split('#js_split#')[2];
			};
		};
		xhr.send(formData);
	};
};

function QADelete(id){
	// 关键字组删除
	var xhr = new XMLHttpRequest(),
		form = document.getElementById('form'+id);
	xhr.open('GET', '?delete='+id, true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			form.parentNode.removeChild(form);
		};
	};
	xhr.send();
};
</script>
{% endblock %}

lab/webotconf/templates/webotconf/webot.html
{% extends 'base2.html' %}
{% block title %}微信配置{% endblock %}
{% block nav_bar %}
	{% include 'labcrm/tools/nav_bar.html' with tag_webot="active" %}
{% endblock %}
{% block row-left %}
<ul class="nav nav-pills nav-stacked nav-stacked text-center">
<!--
{% if is_strict == 'True' %}
	<li role="presentation" class="nav"><a href='{% url "webot:rule" %}?strict='>宽松入群规则</a></li>
	<li role="presentation" class="nav active"><a href='{% url "webot:rule" %}?strict=1'>严格入群规则</a></li>
{% elif is_strict == 'False' %}
	<li role="presentation" class="nav active"><a href='{% url "webot:rule" %}?strict='>宽松入群规则</a></li>
	<li role="presentation" class="nav"><a href='{% url "webot:rule" %}?strict=1'>严格入群规则</a></li>
{% endif %}-->
	<li role="presentation" class="nav {% if is_strict == 'False' %}active{% endif %}"><a href='{% url "webot:rule" %}?strict='>宽松入群规则</a></li>
	<li role="presentation" class="nav {% if is_strict == 'True' %}active{% endif %}"><a href='{% url "webot:rule" %}?strict=1'>严格入群规则</a></li>
	<!--li role="presentation" class="nav {% if is_strict_qa == 'False' %}active{% endif %}"><a href='{% url "webot:qa" %}'>宽松问答配置</a></li-->
	<li role="presentation" class="nav {% if is_strict_qa == 'False' %}active{% endif %}"><a href='#'>宽松问答配置</a></li>
	<li role="presentation" class="nav {% if is_strict_qa == 'True' %}active{% endif %}"><a href='{% url "webot:qas" %}'>严格问答配置</a></li>
	<li role="presentation" class="nav {% if is_pic %}active{% endif %}"><a href='{% url "webot:pic" %}'>活动图片回复</a></li>
</ul>
<hr />
{% block buttons %}
<button type="button" class="btn btn-info btn-lg btn-block unhid hidSwith" onclick='ruleConf()'>更改配置</button>
<button type="submit" class="btn btn-success btn-lg btn-block hidden hidSwith" form='tagForm' onclick='confSave()'>保存配置</button>
<button type="button" class="btn btn-danger btn-lg btn-block hidden hidSwith" onclick='confCancel()'>取消更改</button>
{% endblock %}
{% endblock %}
{% block row-right %}
{% include 'webotconf/ajax/rules.html' %}
{% endblock %}
{% block script %}
<script>
function hidSwith(){
// 按钮显示与隐藏
	var btns = document.getElementsByClassName("hidSwith");
	for(var i=0;i<btns.length;i++){
		var classVal = btns[i].getAttribute("class");
		if(classVal.match('hidden')){
			classVal = classVal.replace('hidden', 'unhid');
		}else{
			classVal = classVal.replace('unhid', 'hidden');
		};
		btns[i].setAttribute("class", classVal);
	};
};

function ruleConf(){
	// ajax 入群规则配置
	hidSwith();
	reset();	
};

function confSave(){
	// 保存配置
	//hidSwith();
	document.getElementById("tagForm").onsubmit = function(e){
		e.preventDefault();
		console.log(e);
		var f = e.target,
			formData = new FormData(f),
			para = document.getElementById('row-right'),
			xhr = new XMLHttpRequest();
		console.log(formData);
		console.log(f);
		xhr.open("POST", f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var rowNew = xhr.responseText;
				if(rowNew.length>0){
					para.innerHTML = rowNew;
					hidSwith();
				}else{
					alert('群名重复，结果未保存。');
					reset();
				};
			};
		};
		xhr.send(formData);
	};
};

function confCancel(){
	// 取消更改
	hidSwith();
	var formRule = document.getElementById('formRule');
	formRule.innerHTML = '\
		{% for room in rooms %}\
		<tr>\
			<td class="input-lg">\
			{% if is_strict == "True" %}\
				{{ room|cut:"#" }}\
			{% else %}\
				{{ room }}\
			{% endif %}\
			</td>\
			<td class="input-lg">\
			{% for rule in room.rules.all %}\
				{{ rule.keyword }}\
			{% endfor %}\
			</td>\
			<td class="input-lg text-center">\
			{% if is_strict == "True" %}\
				{{ room.order|add:-100 }}\
			{% else %}\
				{{ room.order }}\
			{% endif %}\
			</td>\
		</tr>\
		{% endfor %}'
};

function ruleMore(){
	// 新增规则
	var formRule = document.getElementById('formRule'),
		tr = document.createElement('tr');
	formRule.appendChild(tr);
	tr.innerHTML = '\
		<td class="input-lg">\
			<fieldset>\
				<input class="form-control input-lg" name="rooms" type="text" placeholder="群名" list="roomOption" onfocus="this.select();">\
				<datalist id="roomOption">\
				{% for roomOpt in rooms %}\
					<option value="{{ roomOpt }}">\
				{% endfor %}\
				</datalist>\
			</fieldset>\
		</td>\
		<td class="input-lg">\
			<input class="form-control input-lg" name="keywords" type="text" placeholder="关键字集" onfocus="this.select();">\
		</td>\
		<td class="input-lg text-center">\
			<input class="form-control input-lg" name="orders" type="text" placeholder="< 100" onfocus="this.select();">\
		</td>'
};

function reset(func){
	// 重置入群规则配置
	var para = document.getElementById('row-right'),
		xhr = new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			var rowNew = xhr.responseText;
			para.innerHTML = rowNew;
			if(func){
				func();
			};
		};
	};
	xhr.open("GET", '{% url "webot:ajax:modify" %}?strict={{ is_strict }}', true);
	xhr.send();
};
</script>
{% endblock %}