lab/lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='homepage'),
    url(r'^accounts/', include('account.urls', namespace='accounts')),
    url(r'^crm/', include('labcrm.urls', namespace='crm')),
    url(r'^webot/', include('webotconf.urls', namespace='webot')),
    url(r'^group/', include('group.urls', namespace='group')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/labcrm/urls.py
from django.conf.urls import url, include
from labcrm import views


ajax_urls = [
    url(r'^preview', views.ajax_conf_preview, name='preview'),
    # url(r'^modify', views.ajax_detail_modify, name='modify'),
    url(r'^add', views.ajax_conf_add, name='add'),
    url(r'^del', views.ajax_user_del, name='del'),
    url(r'^new', views.ajax_new_user, name='new')
]

modify_urls = [
    url(r'^schedule', views.modify_schedule, name='schedule')
]


urlpatterns = [
    url(r'^ajax/', include(ajax_urls, namespace='ajax')),
    url(r'^modify/', include(modify_urls, namespace='modify')),
    url(r'^users', views.user_list, name='list'),
    url(r'^userclass', views.user_class, name='userclass'),
    url(r'^detail/(?P<new_id>.*)$', views.user_detail, name='detail2'),
    url(r'^detail', views.user_detail, name='detail'),
    url(r'^papers', views.papers_create, name='papers'),
    url(r'^paper/(?P<data_key>\d*)$', views.paper_display, name='paper2'),
    url(r'^paper', views.paper_display, name='paper'),
    url(r'^conf', views.ques_conf, name='conf'),
    url(r'^fill/(?P<data_key>\d*)$', views.ques_fill, name='fill'),
    url(r'^fill', views.ques_fill, name='fill2'),
    url(r'^class', views.link_to_class, name='class'),
    url(r'^courses', views.learning_courses, name='courses'),
    url(r'^statistic', views.subject_statistic, name='statistic'),
    url(r'^schedule', views.schedule_statistic, name='schedule'),
]

lab/labcrm/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from group.models import StudentGroup

class LabUser(models.Model):
    """
    用户
    """
    # relate_name:让关联的对象反查到源对象
    # on_delete:models.CASCADE级联删除
    user = models.OneToOneField(User, verbose_name='用户', on_delete=models.CASCADE, related_name='labuser')
    nickname = models.CharField(max_length=30, verbose_name='用户名', null=True, blank=True)
    wechat = models.CharField(max_length=30, verbose_name='微信号', blank=True, null=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    class_id = models.IntegerField(verbose_name='教室ID', blank=True, null=True)
    # teach_assistance
    ta = models.CharField(max_length=30, verbose_name='助教', default='暂无')
    # json 格式可扩充字段，{course_id: status}
    # status ={1: 期中, 2: 期末, 3: 期中+期末}
    statistic = models.TextField(verbose_name='完课统计', default='{}')
    CLASS_CHOICES = (
        (0, '无'),
        (1, '基础班'),
        (2, '实战班'),
    )
    classification = models.IntegerField(verbose_name='学员类别', default=0, choices=CLASS_CHOICES)
    group = models.ForeignKey(to=StudentGroup, related_name="groupusers", blank=True, null=True)

    def __str__(self):
        return self.user.username


class Paper(models.Model):
    """
    问卷
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='papers', null=True, blank=True)
    create_time = models.DateTimeField(verbose_name='建表时间', auto_now_add=True)
    finished_time = models.DateTimeField(verbose_name='填写时间', null=True, blank=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    is_fill = models.BooleanField(verbose_name='是否填写', default=False)
    key = models.IntegerField(verbose_name='秘钥')
    data = models.TextField(verbose_name='问卷数据')
    mark = models.CharField(verbose_name='标记', max_length=50, default='默认')

    def __str__(self):
        if self.finished_time:
            name = self.mark + ' ' + self.finished_time.strftime('%Y-%m-%d')
        else:
            name = self.mark + ' ' + self.create_time.strftime('%Y-%m-%d')
        return name


class UserAttr(models.Model):
    """
    用户属性
    """
    attr = models.CharField(verbose_name='属性', max_length=255)
    is_option = models.BooleanField(verbose_name='是否提供选项', default=False)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.attr


class AttrOption(models.Model):
    """
    属性预选项
    """
    option = models.CharField(verbose_name='选项', max_length=255)
    attr = models.ForeignKey(UserAttr, verbose_name='属性', related_name='options')

    def __str__(self):
        return self.option


class UserInfoQ(models.Model):
    """
    用户属性提问
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='questions')
    paper = models.ForeignKey(Paper, verbose_name='问卷', related_name='questions', blank=True, null=True)
    attr = models.ForeignKey(UserAttr, verbose_name='属性', related_name='questions')
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.attr.attr


class UserInfoA(models.Model):
    """
    用户属性回答
    """
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(UserInfoQ, verbose_name='问题', on_delete=models.CASCADE, related_name='answers')
    answer = models.CharField(verbose_name='回答', max_length=255)
    create_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def __str__(self):
        return self.answer


class Dialog(models.Model):
    """
    对话记录
    """
    dialog = models.TextField(verbose_name='对话记录')
    user = models.ForeignKey(LabUser, verbose_name='用户', related_name='dialogs')
    recorder = models.ForeignKey(User, verbose_name='记录员')
    log_time = models.DateTimeField(verbose_name='记录时间', auto_now_add=True)

    def __str__(self):
        name = self.user.nickname + ' ' + self.log_time.strftime('%Y-%m-%d')
        return name


class PicData(models.Model):
    """
    图片数据
    """
    pic = models.ImageField(verbose_name='地址', upload_to='img/gallery', unique=True)
    create_time = models.DateTimeField(verbose_name='上传时间', auto_now_add=True)
    name = models.CharField(verbose_name='图片名', max_length=50)

    def __str__(self):
        return self.name


class UserPic(models.Model):
    """
    用户图片
    """
    pic = models.ForeignKey(PicData, verbose_name='图片', on_delete=models.CASCADE, related_name='upic')
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='upic')
    pic_type = models.CharField(verbose_name='图片类型', max_length=30, default='NoType')

    def __str__(self):
        return self.pic.name


class LearnedCourse(models.Model):
    """
    已学课程
    """
    # 利用选项设置 course_id 索引，查看课程方法 get_course_id_display()
    COURSE_CHOICES = (
        (0, '课外课程'),
        (1, 'Python 零基础入门'),
        (2, '爬虫实战'),
        (3, '开发训练营')
    )
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='courses')
    title = models.CharField(max_length=255, verbose_name='课程题目')
    learn_time = models.DateTimeField(verbose_name='学习时间')
    is_inner = models.BooleanField(verbose_name='内部课程', default=True)
    course_id = models.IntegerField(verbose_name='科目ID', default=0, choices=COURSE_CHOICES)

    def __str__(self):
        return self.title


class LearningSchedule(models.Model):
    """
    学习进度
    """
    COURSE_CHOICES = LearnedCourse.COURSE_CHOICES
    SCHEDULE_CHOICES = (
        (1, '入门'),
        (2, '基础'),
        (3, '项目')
    )
    course_id = models.IntegerField(verbose_name='科目ID', default=0, choices=COURSE_CHOICES)
    schedule = models.IntegerField(verbose_name='学习阶段', choices=SCHEDULE_CHOICES)
    user = models.ForeignKey(LabUser, verbose_name='用户', on_delete=models.CASCADE, related_name='schedule')
    note = models.CharField(verbose_name='备注', max_length=255)

    def __str__(self):
        return '{name} - {course}'.format(name=self.user.nickname, course=dict(self.COURSE_CHOICES)[self.course_id])

# GENDER_CHOICES = (
#     ('S', '保密'),
#     ('M', '男'),
#     ('F', '女'),
# )
# AGE_CHOICES = (
#     ('S', '保密'),  # Secret
#     ('C', '童年'),  # Childhood
#     ('J', '少年'),  # Juvenile
#     ('P', '青年'),  # Puberty
#     ('P', '壮年'),  # Prime of life
#     ('M', '中年'),  # Middle-aged
#     ('O', '老年'),  # Old Age
# )
# age = models.CharField(max_length=2, default='S', choices=AGE_CHOICES)
# gender = models.CharField(max_length=2, default='S', choices=GENDER_CHOICES)
# etc = models.TextField()

lab/labcrm/templates/labcrm/ajax/course_list.html
{% if add_new %}
<td class='newIndex'></td>
{% else %}
<td>{{ forloop.revcounter }}</td>
{% endif %}
<td>{{ course.title }}</td>
{% if course.is_inner %}
<td>{{ course.learn_time|date:"Y-m-d H:i" }}</td>
{% else %}
<td>{{ course.learn_time|date:"Y-m-d" }}</td>
{% endif %}
<td>{{ course.is_inner }}</td>

lab/labcrm/templates/labcrm/ajax/papers.html
{% for paper in papers %}
<tr class='text-center' id='paper{{ paper.id }}'>
	<td>
		<a target='_blank' class='btn btn-link' href='{% url "crm:paper" %}/{{ paper.key }}{{ paper.user.id }}'>{{ paper }}</a>
	</td>
	{% if PType != 'M' %}
	<td>
		{% if paper.user %}
		<a target='_blank' class='btn btn-link' href='{% url "crm:detail" %}?uid={{ paper.user.id }}'>{{ paper.user }}</a>
		{% else %}
			-
		{% endif %}
	</td>
	{% endif %}
	<td>
		{{ paper.create_time|date:"Y-m-d H:i:s" }}
	</td>
	{% if PType == 'A' or PType == 'F' %}
	<td>
		{% if paper.finished_time %}
			{{ paper.finished_time|date:"Y-m-d H:i:s" }}
		{% else %}
			-
		{% endif %}
	</td>
	{% endif %}
	<td>
	{% if paper.is_fill %}
		<a tabindex="0" class="btn close btn-block" aria-label="Close" role="button" data-toggle="popover" data-placement="left" data-trigger="focus"  data-content="无法删除已填写问卷" disabled>
			<span aria-hidden="true" style='color:red'>&times;</span>
		</a>
	{% else %}
		<button type="button" class="btn close btn-block" aria-label="Close" onclick='paperDel({{ paper.id }})'>
			<span aria-hidden="true" style='color:red'>&times;</span>
		</button>
	{% endif %}
	</td>
</tr>
{% endfor %}

lab/labcrm/templates/labcrm/ajax/preview.html
<!-- 配置页面 para: ques_cond boxPreview -->
<form method='POST' class="form-horizontal" action='' id='formToFill'>
{% csrf_token %}
	<div class="form-group has-warning">
		<div class="col-md-10 col-md-offset-1">
			<input type="text" class="form-control" name='paper_title' placeholder="标题" onfocus="this.select()">
		</div>
	</div>
	<div class="form-group has-warning">
		<label class='col-xs-1 control-label' for='mark'>标记</label>
		<div class='col-xs-3'>
			<input class='form-control' name='mark' id='mark' placeholder='标记'>
		</div>
		<label class="col-xs-1 col-xs-offset-4 control-label" for='labUser'>TO -- </label>
		<fieldset class="form-group col-xs-3" id='labUser'>
			<input class="form-control" name="labUser" type="text" placeholder="学员" list="userSelect">
			<datalist id="userSelect">
			{% for labUser in users %}
				<option value="{{ labUser }}">
			{% endfor %}
			</datalist>
		</fieldset>
	</div>
	<div class="form-group has-warning">
		<div class="col-md-12">
			<input type="textarea" class="form-control" name='paper_desc' placeholder="描述" onfocus="this.select()">
		</div>
	</div>
	<div id='previewAttrs'>
	{% for attr in attrs %}
	<hr />
	<div class="form-group has-success">
		<label class="col-lg-2" for='labUser{{ attr.id }}'><input class='form-control' name='ques_desc' onfocus="this.select()" value={{ attr.attr }}></label>
		<div class='col-lg-9 col-lg-offset-1'>
		{% if attr.is_option %}
			{% for option in attr.options.all %}
			<div class='radio'>
				<label>
					<input type="radio" name="ques_value" value="{{ option.id }}" disabled>
					{{ option.option }}
				</label>
			</div>
			{% endfor %}
		{% else %}
			<input type='text' id='labUser{{ attr.id }}' class='form-control' name='ques_value' onfocus="this.select()" placeholder='请填写' disabled>
		{% endif %}
		</div>
		<div class='hidden'>
			<input name='attr_id' value='{{ attr.id }}'>
		</div>
	</div>
	{% endfor %}
	</div>
</form>

lab/labcrm/templates/labcrm/ajax/user_add.html
<td class='unhid hidSwith'>
	<a href='{% url "crm:detail" %}?uid={{ lab_user.id }}'>{{ lab_user }}</a>
</td>
<td class='info hidden hidSwith'>
	<a href='#zz' class='username' style='color:red' onclick='inputThis(this)'>{{ lab_user }}</a>
</td>
{% if not data_key %}
	{% if lab_user.nickname %}
	<td class='unhid hidSwith'>
		<a href='{% url "crm:class" %}?uid={{ lab_user.id }}' target='_blank'>{{ lab_user.nickname }}</a>
	</td>
	<td class='info hidden hidSwith'>
		<a href='#zz' class='nickname' style='color:red' onclick='inputThis(this)'>{{ lab_user.nickname }}</a>
	</td>
	{% else %}
	<td class='info unhid hidSwith'>
		<a href='#zz' style='color:red' onclick='newAttrAdd(this, "addUsername")'>添加用户名</a>
	</td>
	<td class='info hidden hidSwith'>
		<a href='#zz' class='nickname' style='color:red' onclick='inputThis(this)'>添加用户名</a>
	</td>
	{% endif %}
{% endif %}
{% if lab_user.wechat %}
<td class='unhid hidSwith'>{{ lab_user.wechat }}</td>
<td class='info hidden hidSwith'>
	<a href='#zz' class='wechat' style='color:red' onclick='inputThis(this)'>{{ lab_user.wechat }}</a>
</td>
{% else %}
<td class='info unhid hidSwith'>
	<a href='#zz' style='color:red' onclick='newAttrAdd(this, "addWechat")'>添加微信号</a>
</td>
<td class='info hidden hidSwith'>
	<a href='#zz' class='wechat' style='color:red' onclick='inputThis(this)'>添加微信号</a>
</td>
{% endif %}
<td class='unhid hidSwith'>{{ lab_user.ta }}</td>
<td class='info hidden hidSwith'>
	<a href='#zz' class='ta' style='color:red' onclick='inputThis(this)'>{{ lab_user.ta }}</a>
</td>
{% if lab_user.papers.last %}
<td>
	<a href='{% url "crm:paper" %}?data_key={{ lab_user.papers.last.key }}{{ lab_user.id }}'>{{ lab_user.papers.last }}</a>
</td>
{% elif data_key %}
<td class='info'>
	<a style='color:red'>添加问卷</a>
</td>
{% else %}
<td class='info'>
	<a href='{% url "crm:conf" %}' style='color:red'>添加问卷</a>
</td>
{% endif %}
<td>{{ lab_user.user.date_joined|date:"Y-m-d" }}</td>
<td>{{ lab_user.dialogs.last.log_time|date:"Y-m-d" }}</td>
{% if data_key %}
<td>
	<input type='checkbox' name='userId' value='{{ lab_user.id }}'>
</td>
{% else %}
<td>
	<option value={{lab_user.classification}} selected>{{lab_user.get_classification_display}}</option>
	<!-- <select id='selectclassificationvalue' name="selectclassification"  class="visible-lg-inline visible-sm-inline visible-md-inline" >
		<option value={{lab_user.classification}} selected>{{lab_user.get_classification_display}}</option>		
		{% for class in classification %}
			{% if lab_user.classification != class.0 %}
				<option value={{class.0}}>{{ class.1 }}</option>
			{% endif %}		
	    {% endfor %}  
	</select> -->
</td>
<td class='hidden tbHid'>
	<input form='formUserDel' type='checkbox' name='userId' value='{{ lab_user.id }}'>
</td>
{% endif %}

lab/labcrm/templates/labcrm/ajax/user_del.html
{% for lab_user in users %}
<tr id='user{{ lab_user.id }}'>
	{% include 'labcrm/ajax/user_add.html' %}
</tr>
{% endfor %}